In [1]:
import pandas as pd
import statsmodels.regression.linear_model as ls
import statsmodels.tools.tools as ct
import numpy as np
import matplotlib
from statsmodels.formula.api import ols
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression

In [2]:
import yfinance as yf

In [3]:
AAPL = yf.Ticker('MMM')
AAPL
AAPL.financials

,2020-12-31,2019-12-31,2018-12-31,2017-12-31
Research Development,1862000000.0,1874000000.0,1816000000.0,1862000000.0
Effect Of Accounting Charges,None,None,None,None
Income Before Tax,6706000000.0,5712000000.0,7000000000.0,7548000000.0
Minority Interest,64000000.0,63000000.0,52000000.0,59000000.0
Net Income,5384000000.0,4570000000.0,5349000000.0,4858000000.0
Selling General Administrative,6751000000.0,6390000000.0,6527000000.0,6493000000.0
Gross Profit,15685000000.0,15400000000.0,16110000000.0,15688000000.0
Ebit,7072000000.0,7136000000.0,7767000000.0,7333000000.0
Operating Income,7072000000.0,7136000000.0,7767000000.0,7333000000.0
Other Operating Expenses,None,None,None,None
Interest Expense,-529000000.0,-448000000.0,-350000000.0,-322000000.0
Extraordinary Items,None,None,None,None
Non Recurring,None,None,None,None
Other Items,None,None,None,None
Income Tax Expense,1318000000.0,1130000000.0,1637000000.0,2679000000.0
Total Revenue,32184000000.0,32136000000.0,32765000000.0,31657000000.0
Total Operating Expenses,25112000000.0,25000000000.0,24998000000.0,24324000000.0
Cost Of Revenue,16499000000.0,16736000000.0,16655000000.0,15969000000.0
Total Other Income Expense Net,-366000000.0,-1424000000.0,-767000000.0,215000000.0
Discontinued Operations,None,None,None,None
Net Income From Continuing Ops,5388000000.0,4582000000.0,5363000000.0,4869000000.0
Net Income Applicable To Common Shares,5384000000.0,4570000000.0,5349000000.0,4858000000.0

In [4]:
aapl = AAPL.info
aapl['regularMarketPreviousClose'] == None
aapl

{'zip': '55144-1000',
 'sector': 'Industrials',
 'fullTimeEmployees': 95000,
 'longBusinessSummary': '3M Company develops, manufactures, and markets various products worldwide. It operates through four business segments: Safety and Industrial, Transportation and Electronics, Health Care, and Consumer. The Safety and Industrial segment offers personal safety products, industrial adhesives and tapes, abrasives, closure and masking systems, electrical markets, automotive aftermarket, and roofing granules to industrial, electrical, and safety markets. The Transportation and Electronics provides electronics, such as display materials and systems, electronic materials solutions; automotive and aerospace, and commercial solutions; advanced materials; and transportation safety products to transportation and electronic original equipment manufacturer customers. The Health Care segment offers medical and surgical supplies, skin health and infection prevention products, oral care, separation and purification sciences, health information systems, drug delivery systems, and food safety products to healthcare industry. The Consumer segment provides home improvement, home care, and consumer health care products, as well as stationery and office supplies to various consumers. This segment is also involved in the retail auto care business. It offers its products through various e-commerce and traditional wholesalers, retailers, jobbers, distributors, and dealers, as well as directly to users. 3M Company has a strategic collaboration with Merry Maids in residential cleaning sector; and collaborations with The Infectious Disease Research Institute and Duke Human Vaccine Institute to create a vaccine candidate with potential to provide protection against multiple variants of SARS-CoV-2. The company was founded in 1902 and is headquartered in St. Paul, Minnesota.',
 'city': 'St. Paul',
 'phone': '651-733-1110',
 'state': 'MN',
 'country': 'United States',
 'companyOfficers': [],
 'website': 'http://www.3m.com',
 'maxAge': 1,
 'address1': '3M Center',
 'industry': 'Specialty Industrial Machinery',
 'ebitdaMargins': 0.29003,
 'profitMargins': 0.17038,
 'grossMargins': 0.48703998,
 'operatingCashflow': 8569999872,
 'revenueGrowth': 0.247,
 'operatingMargins': 0.23501000000000002,
 'ebitda': 10074000384,
 'targetLowPrice': 138,
 'recommendationKey': 'hold',
 'grossProfits': 15685000000,
 'freeCashflow': 5909624832,
 'targetMedianPrice': 206,
 'currentPrice': 181.6807,
 'earningsGrowth': 0.151,
 'currentRatio': 1.7309999999999999,
 'returnOnAssets': 0.10925999,
 'numberOfAnalystOpinions': 16,
 'targetMeanPrice': 198.01,
 'debtToEquity': 131.71,
 'returnOnEquity': 0.46612000000000003,
 'targetHighPrice': 216,
 'totalCash': 5503000064,
 'totalDebt': 19118999552,
 'totalRevenue': 34733998080,
 'totalCashPerShare': 9.51,
 'financialCurrency': 'USD',
 'revenuePerShare': 59.938,
 'quickRatio': 1.112,
 'recommendationMean': 3.1,
 'exchange': 'NYQ',
 'shortName': '3M Company',
 'longName': '3M Company',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'isEsgPopulated': False,
 'gmtOffSetMilliseconds': '-14400000',
 'quoteType': 'EQUITY',
 'symbol': 'MMM',
 'messageBoardId': 'finmb_289194',
 'market': 'us_market',
 'annualHoldingsTurnover': None,
 'enterpriseToRevenue': 3.422,
 'beta3Year': None,
 'enterpriseToEbitda': 11.8,
 '52WeekChange': 0.13753831,
 'morningStarRiskRating': None,
 'forwardEps': 10.69,
 'revenueQuarterlyGrowth': None,
 'sharesOutstanding': 578638016,
 'fundInceptionDate': None,
 'annualReportExpenseRatio': None,
 'totalAssets': None,
 'bookValue': 24.969,
 'sharesShort': 11585487,
 'sharesPercentSharesOut': 0.02,
 'fundFamily': None,
 'lastFiscalYearEnd': 1609372800,
 'heldPercentInstitutions': 0.68785006,
 'netIncomeToCommon': 5918000128,
 'trailingEps': 10.112,
 'lastDividendValue': None,
 'SandP52WeekChange': 0.33207917000000003,
 'priceToBook': 7.2762504,
 'heldPercentInsiders': 0.00116,
 'nextFiscalYearEnd': 1672444800,
 'yield': None,
 'mostRecentQuarter': 1625011200,
 'shortRatio': 4.67,
 'sharesShortPreviousMonthDate': 1628812800,
 'floatShares': 577990178,
 'beta': 0.9530559999999999,
 'enterpriseValue': 118874644480,
 'priceHint': 2,
 'threeYearAverageReturn': None,
 'lastSplitDate': None,
 'lastSplitFactor': None,
 'legalType': None,
 'lastDividendDate': None,
 'morningStarOverallRating': None,
 'earningsQuarterlyGrowth': 0.167,
 'priceToSalesTrailing12Months': 3.0266414,
 'dateShortInterest': 1631664000,
 'pegRatio': 2.19,
 'ytdReturn': None,
 'forwardPE': 16.995388,
 'lastCapGain': None,
 'shortPercentOfFloat': 0.02,
 'sharesShortPriorMonth': 10966691,
 'impliedSharesOutstanding': None,
 'category': None,
 'fiveYearAverageReturn': None,
 'previousClose': 181.79,
 'regularMarketOpen': 181.82,
 'twoHundredDayAverage': 196.43747,
 'trailingAnnualDividendYield': 0.03245503,
 'payoutRatio': 0.5836,
 'volume24Hr': None,
 'regularMarketDayHigh': 182.854,
 'navPrice': None,
 'averageDailyVolume10Day': 2611416,
 'regularMarketPreviousClose': 181.79,
 'fiftyDayAverage': 190.824,
 'trailingAnnualDividendRate': 5.9,
 'open': 181.82,
 'toCurrency': None,
 'averageVolume10days': 2611416,
 'expireDate': None,
 'algorithm': None,
 'dividendRate': 5.92,
 'exDividendDate': 1629417600,
 'circulatingSupply': None,
 'startDate': None,
 'regularMarketDayLow': 180.71,
 'currency': 'USD',
 'trailingPE': 17.96684,
 'regularMarketVolume': 399192,
 'lastMarket': None,
 'maxSupply': None,
 'openInterest': None,
 'marketCap': 105127354368,
 'volumeAllCurrencies': None,
 'strikePrice': None,
 'averageVolume': 2383726,
 'dayLow': 180.71,
 'ask': 181.56,
 'askSize': 1300,
 'volume': 399192,
 'fiftyTwoWeekHigh': 208.95,
 'fromCurrency': None,
 'fiveYearAvgDividendYield': 2.89,
 'fiftyTwoWeekLow': 156.13,
 'bid': 181.56,
 'tradeable': False,
 'dividendYield': 0.032600000000000004,
 'bidSize': 1200,
 'dayHigh': 182.854,
 'regularMarketPrice': 181.6807,
 'logo_url': 'https://logo.clearbit.com/3m.com'}

In [5]:
SPchange= aapl['SandP52WeekChange']
SPchange

0.33207917000000003

In [6]:
df = AAPL.history(period='1y')

In [7]:
last_year = df['Close'][0]

In [8]:
today= df['Close'][-1]

In [9]:
ytd = (today-last_year)/last_year *100

In [10]:
ytd

16.016621411954805

In [11]:
# There are 2 tables on the Wikipedia page
# we want the first table

payload=pd.read_html('https://en.wikipedia.org/wiki/List_of_S%26P_500_companies')
first_table = payload[0]
second_table = payload[1]

df = first_table

In [12]:
df

,Symbol,Security,SEC filings,GICS Sector,GICS Sub-Industry,Headquarters Location,Date first added,CIK,Founded
0,MMM,3M,reports,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1976-08-09,66740,1902
1,ABT,Abbott Laboratories,reports,Health Care,Health Care Equipment,"North Chicago, Illinois",1964-03-31,1800,1888
2,ABBV,AbbVie,reports,Health Care,Pharmaceuticals,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
3,ABMD,Abiomed,reports,Health Care,Health Care Equipment,"Danvers, Massachusetts",2018-05-31,815094,1981
4,ACN,Accenture,reports,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989
...,...,...,...,...,...,...,...,...,...
500,YUM,Yum! Brands,reports,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,1997
501,ZBRA,Zebra Technologies,reports,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969
502,ZBH,Zimmer Biomet,reports,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,1927
503,ZION,Zions Bancorp,reports,Financials,Regional Banks,"Salt Lake City, Utah",2001-06-22,109380,1873
504,ZTS,Zoetis,reports,Health Care,Pharmaceuticals,"Parsippany, New Jersey",2013-06-21,1555280,1952

In [13]:
symbols = df['Symbol'].values.tolist()
print(symbols[:15])

names = df['Security'].values.tolist()
print(names[:15])
for i in range(len(symbols)):
    if symbols[i] == 'BF.B':
        print (i)
#symbols.pop(64)
#symbols.pop(80)

['MMM', 'ABT', 'ABBV', 'ABMD', 'ACN', 'ATVI', 'ADBE', 'AMD', 'AAP', 'AES', 'AFL', 'A', 'APD', 'AKAM', 'ALK']
['3M', 'Abbott Laboratories', 'AbbVie', 'Abiomed', 'Accenture', 'Activision Blizzard', 'Adobe', 'Advanced Micro Devices', 'Advance Auto Parts', 'AES Corp', 'Aflac', 'Agilent Technologies', 'Air Products & Chemicals', 'Akamai Technologies', 'Alaska Air Group']
80

In [14]:
#symbols

In [15]:
apt = pd.DataFrame()
stock_list=[]
ytd_list=[]
pegRatio_list=[]
currentRatio_list = []
book_value=[]
dividend_yield=[]
moving_average_200 = []
priceToBook = []
for i in symbols:
    stock = yf.Ticker(i)
    stock1 = stock.info
    if stock1['regularMarketPreviousClose'] != None:
        pegRatio = stock1['pegRatio']
        history = stock.history(period='1y')
        last_year = history['Close'][0]
        today= history['Close'][-1]
        ytd = (today-last_year)/last_year
        ytd_list.append(ytd)
        pegRatio_list.append(pegRatio)
        stock_list.append(i)
        currentRatio_list.append(stock1['currentRatio'])
        book_value.append(stock1['bookValue'])
        dividend_yield.append(stock1['fiveYearAvgDividendYield'])
        moving_average_200.append(stock1['twoHundredDayAverage'])
        priceToBook.append(stock1['priceToBook'])
        print(i)
    else:
        continue

MMM
ABT
ABBV
ABMD
ACN
ATVI
ADBE
AMD
AAP
AES
AFL
A
APD
AKAM
ALK
ALB
ARE
ALGN
ALLE
LNT
ALL
GOOGL
GOOG
MO
AMZN
AMCR
AEE
AAL
AEP
AXP
AIG
AMT
AWK
AMP
ABC
AME
AMGN
APH
ADI
ANSS
ANTM
AON
AOS
APA
AAPL
AMAT
APTV
ADM
ANET
AJG
AIZ
T
ATO
ADSK
ADP
AZO
AVB
AVY
BKR
BLL
BAC
BBWI
BAX
BDX
BBY
BIO
TECH
BIIB
BLK
BK
BA
BKNG
BWA
BXP
BSX
BMY
AVGO
BR
BRO
CHRW
COG
CDNS
CZR
CPB
COF
CAH
KMX
CCL
CARR
CTLT
CAT
CBOE
CBRE
CDW
CE
CNC
CNP
CDAY
CERN
CF
CRL
SCHW
CHTR
CVX
CMG
CB
CHD
CI
CINF
CTAS
CSCO
C
CFG
CTXS
CLX
CME
CMS
KO
CTSH
CL
CMCSA
CMA
CAG
COP
ED
STZ
COO
CPRT
GLW
CTVA
COST
CCI
CSX
CMI
CVS
DHI
DHR
DRI
DVA
DE
DAL
XRAY
DVN
DXCM
FANG
DLR
DFS
DISCA
DISCK
DISH
DG
DLTR
D
DPZ
DOV
DOW
DTE
DUK
DRE
DD
DXC
EMN
ETN
EBAY
ECL
EIX
EW
EA
EMR
ENPH
ETR
EOG
EFX
EQIX
EQR
ESS
EL
ETSY
EVRG
ES
RE
EXC
EXPE
EXPD
EXR
XOM
FFIV
FB
FAST
FRT
FDX
FIS
FITB
FE
FRC
FISV
FLT
FMC
F
FTNT
FTV
FBHS
FOXA
FOX
BEN
FCX
GPS
GRMN
IT
GNRC
GD
GE
GIS
GM
GPC
GILD
GL
GPN
GS
GWW
HAL
HBI
HIG
HAS
HCA
PEAK
HSIC
HSY
HES
HPE
HLT
HOLX
HD
HON
HRL
HST
HWM
HPQ
HUM
HBAN
HII
IEX
IDXX
INFO
ITW
ILMN
INCY
IR
INTC
ICE
IBM
IP
IPG
IFF
INTU
ISRG
IVZ
IPGP
IQV
IRM
JKHY
J
JBHT
SJM
JNJ
JCI
JPM
JNPR
KSU
K
KEY
KEYS
KMB
KIM
KMI
KLAC
KHC
KR
LHX
LH
LRCX
LW
LVS
LEG
LDOS
LEN
LLY
LNC
LIN
LYV
LKQ
LMT
L
LOW
LUMN
LYB
MTB
MRO
MPC
MKTX
MAR
MMC
MLM
MAS
MA
MTCH
MKC
MCD
MCK
MDT
MRK
MET
MTD
MGM
MCHP
MU
MSFT
MAA
MRNA
MHK
TAP
MDLZ
MPWR
MNST
MCO
MS
MOS
MSI
MSCI
NDAQ
NTAP
NFLX
NWL
NEM
NWSA
NWS
NEE
NLSN
NKE
NI
NSC
NTRS
NOC
NLOK
NCLH
NRG
NUE
NVDA
NVR
NXPI
ORLY
OXY
ODFL
OMC
OKE
ORCL
OGN
OTIS
PCAR
PKG
PH
PAYX
PAYC
PYPL
PENN
PNR
PBCT
PEP
PKI
PFE
PM
PSX
PNW
PXD
PNC
POOL
PPG
PPL
PFG
PG
PGR
PLD
PRU
PTC
PEG
PSA
PHM
PVH
QRVO
PWR
QCOM
DGX
RL
RJF
RTX
O
REG
REGN
RF
RSG
RMD
RHI
ROK
ROL
ROP
ROST
RCL
SPGI
CRM
SBAC
SLB
STX
SEE
SRE
NOW
SHW
SPG
SWKS
SNA
SO
LUV
SWK
SBUX
STT
STE
SYK
SIVB
SYF
SNPS
SYY
TMUS
TROW
TTWO
TPR
TGT
TEL
TDY
TFX
TER
TSLA
TXN
TXT
TMO
TJX
TSCO
TT
TDG
TRV
TRMB
TFC
TWTR
TYL
TSN
UDR
ULTA
USB
UAA
UA
UNP
UAL
UNH
UPS
URI
UHS
VLO
VTR
VRSN
VRSK
VZ
VRTX
VFC
VIAC
VTRS
V
VNO
VMC
WRB
WAB
WMT
WBA
DIS
WM
WAT
WEC
WFC
WELL
WST
WDC
WU
WRK
WY
WHR
WMB
WLTW
WYNN
XEL
XLNX
XYL
YUM
ZBRA
ZBH
ZION
ZTS

In [27]:
df = pd.DataFrame()

In [37]:
df['stock_list']= stock_list
df['pegRatio_list']= pegRatio_list
df['ytd_list']= ytd_list
df['currentRatio_list'] = currentRatio_list
#df['book_value'] = book_value
df['dividend_yield'] = dividend_yield
df['moving_average_200'] = moving_average_200 
df['priceToBook'] = priceToBook

df = df.dropna()

In [39]:
list(df.columns)

['stock_list',
 'pegRatio_list',
 'ytd_list',
 'currentRatio_list',
 'dividend_yield',
 'moving_average_200',
 'priceToBook']

0.02

In [41]:
from sklearn.preprocessing import MinMaxScaler

#normData = pd.DataFrame(scaler.transform(df), index=df.index, columns=df.columns)
#scalers = {}
# def norm(columns):
#     for column in columns:
#         min_max_scaler = MinMaxScaler()
#         df[["A", "B"]] = min_max_scaler.fit_transform(df[["A", "B"]])
cols_to_norm = list(df.columns)
cols_to_norm.remove("ytd_list")
cols_to_norm.remove("stock_list")
df[cols_to_norm] = df[cols_to_norm].apply(lambda x: (x - x.min()) / (x.max() - x.min()))

C:\Users\rudra\Anaconda3\lib\site-packages\pandas\core\frame.py:3188: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

In [42]:
df.head()

,stock_list,pegRatio_list,ytd_list,currentRatio_list,dividend_yield,moving_average_200,priceToBook
0,MMM,0.089555,0.160166,0.130369,0.411175,0.218342,0.009948
1,ABT,0.089754,0.152429,0.135380,0.242120,0.127560,0.008367
2,ABBV,0.089076,0.303594,0.064747,0.604585,0.119409,0.021866
4,ACN,0.091539,0.493229,0.092269,0.223496,0.343146,0.014983
5,ATVI,0.088465,-0.068728,0.377028,0.078797,0.091983,0.004486

In [43]:
corrM = df.corr()
corrM

,pegRatio_list,ytd_list,currentRatio_list,dividend_yield,moving_average_200,priceToBook
pegRatio_list,1.000000,-0.069038,0.051214,0.015311,0.024599,-0.013477
ytd_list,-0.069038,1.000000,0.069359,0.080953,-0.030743,-0.047808
currentRatio_list,0.051214,0.069359,1.000000,-0.226655,0.149175,-0.036842
dividend_yield,0.015311,0.080953,-0.226655,1.000000,-0.435916,-0.071555
moving_average_200,0.024599,-0.030743,0.149175,-0.435916,1.000000,0.057594
priceToBook,-0.013477,-0.047808,-0.036842,-0.071555,0.057594,1.000000

In [34]:
#help(pd.qcut)
df['bins'] = pd.qcut(df['pegRatio_list'], 10, labels = ['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th'])
#df['bins'].idxmin()
#df['bins'].idxmax()
df['bins'].value_counts().sort_index()

1st     51
2nd     50
3rd     50
4th     50
5th     52
6th     48
7th     50
8th     50
9th     50
10th    50
Name: bins, dtype: int64

In [37]:
mask = df['bins']== '4th'
y = df.groupby('bins')['ytd_list'].mean()
x = df.groupby('bins')[['pegRatio_list','priceToBook','moving_average_200','dividend_yield','currentRatio_list']].mean()
y_10 = y[9:10]
y_1 = y[:1]


y = y_1[0]-y_10[0]
#x = x_1 - x_10
print(y)

0.3021528542546287

In [36]:
y
x= []

for re in range(5):
    num = x_1.T['1st'][re] - x_10.T['10th'][re]
    x.append(num)
x

NameError: name 'x_1' is not defined

In [31]:
print(x)
print(y)

[]
0.3021528542546287

In [ ]:
model = sm.OLS(y,x, const = 1).fit()
model.summary()

In [209]:
reg = LinearRegression()

In [210]:
reg.fit(x,y)

ValueError: Expected 2D array, got 1D array instead:
array=[-29.62153725  -8.5622072  -94.86418012   0.34987267  -1.78194712].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [211]:
reg.coef_

AttributeError: 'LinearRegression' object has no attribute 'coef_'