In [1]:
import pandas as pd
import statsmodels.regression.linear_model as ls
import statsmodels.tools.tools as ct
import numpy as np
import matplotlib
from statsmodels.formula.api import ols
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression

In [2]:
import yfinance as yf

In [3]:
AAPL = yf.Ticker('MMM')
AAPL
AAPL.financials

,2020-12-31,2019-12-31,2018-12-31,2017-12-31
Research Development,1862000000.0,1874000000.0,1816000000.0,1862000000.0
Effect Of Accounting Charges,None,None,None,None
Income Before Tax,6706000000.0,5712000000.0,7000000000.0,7548000000.0
Minority Interest,64000000.0,63000000.0,52000000.0,59000000.0
Net Income,5384000000.0,4570000000.0,5349000000.0,4858000000.0
Selling General Administrative,6751000000.0,6390000000.0,6527000000.0,6493000000.0
Gross Profit,15685000000.0,15400000000.0,16110000000.0,15688000000.0
Ebit,7072000000.0,7136000000.0,7767000000.0,7333000000.0
Operating Income,7072000000.0,7136000000.0,7767000000.0,7333000000.0
Other Operating Expenses,None,None,None,None
Interest Expense,-529000000.0,-448000000.0,-350000000.0,-322000000.0
Extraordinary Items,None,None,None,None
Non Recurring,None,None,None,None
Other Items,None,None,None,None
Income Tax Expense,1318000000.0,1130000000.0,1637000000.0,2679000000.0
Total Revenue,32184000000.0,32136000000.0,32765000000.0,31657000000.0
Total Operating Expenses,25112000000.0,25000000000.0,24998000000.0,24324000000.0
Cost Of Revenue,16499000000.0,16736000000.0,16655000000.0,15969000000.0
Total Other Income Expense Net,-366000000.0,-1424000000.0,-767000000.0,215000000.0
Discontinued Operations,None,None,None,None
Net Income From Continuing Ops,5388000000.0,4582000000.0,5363000000.0,4869000000.0
Net Income Applicable To Common Shares,5384000000.0,4570000000.0,5349000000.0,4858000000.0

In [4]:
aapl = AAPL.info
aapl['regularMarketPreviousClose'] == None
aapl

{'zip': '55144-1000',
 'sector': 'Industrials',
 'fullTimeEmployees': 95000,
 'longBusinessSummary': '3M Company develops, manufactures, and markets various products worldwide. It operates through four business segments: Safety and Industrial, Transportation and Electronics, Health Care, and Consumer. The Safety and Industrial segment offers personal safety products, industrial adhesives and tapes, abrasives, closure and masking systems, electrical markets, automotive aftermarket, and roofing granules to industrial, electrical, and safety markets. The Transportation and Electronics provides electronics, such as display materials and systems, electronic materials solutions; automotive and aerospace, and commercial solutions; advanced materials; and transportation safety products to transportation and electronic original equipment manufacturer customers. The Health Care segment offers medical and surgical supplies, skin health and infection prevention products, oral care, separation and purification sciences, health information systems, drug delivery systems, and food safety products to healthcare industry. The Consumer segment provides home improvement, home care, and consumer health care products, as well as stationery and office supplies to various consumers. This segment is also involved in the retail auto care business. It offers its products through various e-commerce and traditional wholesalers, retailers, jobbers, distributors, and dealers, as well as directly to users. 3M Company has a strategic collaboration with Merry Maids in residential cleaning sector; and collaborations with The Infectious Disease Research Institute and Duke Human Vaccine Institute to create a vaccine candidate with potential to provide protection against multiple variants of SARS-CoV-2. The company was founded in 1902 and is headquartered in St. Paul, Minnesota.',
 'city': 'St. Paul',
 'phone': '651-733-1110',
 'state': 'MN',
 'country': 'United States',
 'companyOfficers': [],
 'website': 'http://www.3m.com',
 'maxAge': 1,
 'address1': '3M Center',
 'industry': 'Specialty Industrial Machinery',
 'ebitdaMargins': 0.29003,
 'profitMargins': 0.17038,
 'grossMargins': 0.48703998,
 'operatingCashflow': 8569999872,
 'revenueGrowth': 0.247,
 'operatingMargins': 0.23501000000000002,
 'ebitda': 10074000384,
 'targetLowPrice': 138,
 'recommendationKey': 'hold',
 'grossProfits': 15685000000,
 'freeCashflow': 5909624832,
 'targetMedianPrice': 206,
 'currentPrice': 181.6807,
 'earningsGrowth': 0.151,
 'currentRatio': 1.7309999999999999,
 'returnOnAssets': 0.10925999,
 'numberOfAnalystOpinions': 16,
 'targetMeanPrice': 198.01,
 'debtToEquity': 131.71,
 'returnOnEquity': 0.46612000000000003,
 'targetHighPrice': 216,
 'totalCash': 5503000064,
 'totalDebt': 19118999552,
 'totalRevenue': 34733998080,
 'totalCashPerShare': 9.51,
 'financialCurrency': 'USD',
 'revenuePerShare': 59.938,
 'quickRatio': 1.112,
 'recommendationMean': 3.1,
 'exchange': 'NYQ',
 'shortName': '3M Company',
 'longName': '3M Company',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'isEsgPopulated': False,
 'gmtOffSetMilliseconds': '-14400000',
 'quoteType': 'EQUITY',
 'symbol': 'MMM',
 'messageBoardId': 'finmb_289194',
 'market': 'us_market',
 'annualHoldingsTurnover': None,
 'enterpriseToRevenue': 3.422,
 'beta3Year': None,
 'enterpriseToEbitda': 11.8,
 '52WeekChange': 0.13753831,
 'morningStarRiskRating': None,
 'forwardEps': 10.69,
 'revenueQuarterlyGrowth': None,
 'sharesOutstanding': 578638016,
 'fundInceptionDate': None,
 'annualReportExpenseRatio': None,
 'totalAssets': None,
 'bookValue': 24.969,
 'sharesShort': 11585487,
 'sharesPercentSharesOut': 0.02,
 'fundFamily': None,
 'lastFiscalYearEnd': 1609372800,
 'heldPercentInstitutions': 0.68785006,
 'netIncomeToCommon': 5918000128,
 'trailingEps': 10.112,
 'lastDividendValue': None,
 'SandP52WeekChange': 0.33207917000000003,
 'priceToBook': 7.2762504,
 'heldPercentInsiders': 0.00116,
 'nextFiscalYearEnd': 1672444800,
 'yield': None,
 'mostRecentQuarter': 1625011200,
 'shortRatio': 4.67,
 'sharesShortPreviousMonthDate': 1628812800,
 'floatShares': 577990178,
 'beta': 0.9530559999999999,
 'enterpriseValue': 118874644480,
 'priceHint': 2,
 'threeYearAverageReturn': None,
 'lastSplitDate': None,
 'lastSplitFactor': None,
 'legalType': None,
 'lastDividendDate': None,
 'morningStarOverallRating': None,
 'earningsQuarterlyGrowth': 0.167,
 'priceToSalesTrailing12Months': 3.0266414,
 'dateShortInterest': 1631664000,
 'pegRatio': 2.19,
 'ytdReturn': None,
 'forwardPE': 16.995388,
 'lastCapGain': None,
 'shortPercentOfFloat': 0.02,
 'sharesShortPriorMonth': 10966691,
 'impliedSharesOutstanding': None,
 'category': None,
 'fiveYearAverageReturn': None,
 'previousClose': 181.79,
 'regularMarketOpen': 181.82,
 'twoHundredDayAverage': 196.43747,
 'trailingAnnualDividendYield': 0.03245503,
 'payoutRatio': 0.5836,
 'volume24Hr': None,
 'regularMarketDayHigh': 182.854,
 'navPrice': None,
 'averageDailyVolume10Day': 2611416,
 'regularMarketPreviousClose': 181.79,
 'fiftyDayAverage': 190.824,
 'trailingAnnualDividendRate': 5.9,
 'open': 181.82,
 'toCurrency': None,
 'averageVolume10days': 2611416,
 'expireDate': None,
 'algorithm': None,
 'dividendRate': 5.92,
 'exDividendDate': 1629417600,
 'circulatingSupply': None,
 'startDate': None,
 'regularMarketDayLow': 180.71,
 'currency': 'USD',
 'trailingPE': 17.96684,
 'regularMarketVolume': 399192,
 'lastMarket': None,
 'maxSupply': None,
 'openInterest': None,
 'marketCap': 105127354368,
 'volumeAllCurrencies': None,
 'strikePrice': None,
 'averageVolume': 2383726,
 'dayLow': 180.71,
 'ask': 181.56,
 'askSize': 1300,
 'volume': 399192,
 'fiftyTwoWeekHigh': 208.95,
 'fromCurrency': None,
 'fiveYearAvgDividendYield': 2.89,
 'fiftyTwoWeekLow': 156.13,
 'bid': 181.56,
 'tradeable': False,
 'dividendYield': 0.032600000000000004,
 'bidSize': 1200,
 'dayHigh': 182.854,
 'regularMarketPrice': 181.6807,
 'logo_url': 'https://logo.clearbit.com/3m.com'}

In [5]:
SPchange= aapl['SandP52WeekChange']
SPchange

0.33207917000000003

In [6]:
df = AAPL.history(period='1y')

In [7]:
last_year = df['Close'][0]

In [8]:
today= df['Close'][-1]

In [9]:
ytd = (today-last_year)/last_year *100

In [10]:
ytd

16.016621411954805

In [11]:
# There are 2 tables on the Wikipedia page
# we want the first table

payload=pd.read_html('https://en.wikipedia.org/wiki/List_of_S%26P_500_companies')
first_table = payload[0]
second_table = payload[1]

df = first_table

In [12]:
df

,Symbol,Security,SEC filings,GICS Sector,GICS Sub-Industry,Headquarters Location,Date first added,CIK,Founded
0,MMM,3M,reports,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1976-08-09,66740,1902
1,ABT,Abbott Laboratories,reports,Health Care,Health Care Equipment,"North Chicago, Illinois",1964-03-31,1800,1888
2,ABBV,AbbVie,reports,Health Care,Pharmaceuticals,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
3,ABMD,Abiomed,reports,Health Care,Health Care Equipment,"Danvers, Massachusetts",2018-05-31,815094,1981
4,ACN,Accenture,reports,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989
...,...,...,...,...,...,...,...,...,...
500,YUM,Yum! Brands,reports,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,1997
501,ZBRA,Zebra Technologies,reports,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969
502,ZBH,Zimmer Biomet,reports,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,1927
503,ZION,Zions Bancorp,reports,Financials,Regional Banks,"Salt Lake City, Utah",2001-06-22,109380,1873
504,ZTS,Zoetis,reports,Health Care,Pharmaceuticals,"Parsippany, New Jersey",2013-06-21,1555280,1952

In [13]:
symbols = df['Symbol'].values.tolist()
print(symbols[:15])

names = df['Security'].values.tolist()
print(names[:15])
for i in range(len(symbols)):
    if symbols[i] == 'BF.B':
        print (i)
#symbols.pop(64)
#symbols.pop(80)

['MMM', 'ABT', 'ABBV', 'ABMD', 'ACN', 'ATVI', 'ADBE', 'AMD', 'AAP', 'AES', 'AFL', 'A', 'APD', 'AKAM', 'ALK']
['3M', 'Abbott Laboratories', 'AbbVie', 'Abiomed', 'Accenture', 'Activision Blizzard', 'Adobe', 'Advanced Micro Devices', 'Advance Auto Parts', 'AES Corp', 'Aflac', 'Agilent Technologies', 'Air Products & Chemicals', 'Akamai Technologies', 'Alaska Air Group']
80

In [14]:
#symbols

In [15]:
apt = pd.DataFrame()
stock_list=[]
ytd_list=[]
pegRatio_list=[]
currentRatio_list = []
book_value=[]
dividend_yield=[]
moving_average_200 = []
priceToBook = []
for i in symbols:
    stock = yf.Ticker(i)
    stock1 = stock.info
    if stock1['regularMarketPreviousClose'] != None:
        pegRatio = stock1['pegRatio']
        history = stock.history(period='1y')
        last_year = history['Close'][0]
        today= history['Close'][-1]
        ytd = (today-last_year)/last_year
        ytd_list.append(ytd)
        pegRatio_list.append(pegRatio)
        stock_list.append(i)
        currentRatio_list.append(stock1['currentRatio'])
        book_value.append(stock1['bookValue'])
        dividend_yield.append(stock1['fiveYearAvgDividendYield'])
        moving_average_200.append(stock1['twoHundredDayAverage'])
        priceToBook.append(stock1['priceToBook'])
        print(i)
    else:
        continue

MMM
ABT
ABBV
ABMD
ACN
ATVI
ADBE
AMD
AAP
AES
AFL
A
APD
AKAM
ALK
ALB
ARE
ALGN
ALLE
LNT
ALL
GOOGL
GOOG
MO
AMZN
AMCR
AEE
AAL
AEP
AXP
AIG
AMT
AWK
AMP
ABC
AME
AMGN
APH
ADI
ANSS
ANTM
AON
AOS
APA
AAPL
AMAT
APTV
ADM
ANET
AJG
AIZ
T
ATO
ADSK
ADP
AZO
AVB
AVY
BKR
BLL
BAC
BBWI
BAX
BDX
BBY
BIO
TECH
BIIB
BLK
BK
BA
BKNG
BWA
BXP
BSX
BMY
AVGO
BR
BRO
CHRW
COG
CDNS
CZR
CPB
COF
CAH
KMX
CCL
CARR
CTLT
CAT
CBOE
CBRE
CDW
CE
CNC
CNP
CDAY
CERN
CF
CRL
SCHW
CHTR
CVX
CMG
CB
CHD
CI
CINF
CTAS
CSCO
C
CFG
CTXS
CLX
CME
CMS
KO
CTSH
CL
CMCSA
CMA
CAG
COP
ED
STZ
COO
CPRT
GLW
CTVA
COST
CCI
CSX
CMI
CVS
DHI
DHR
DRI
DVA
DE
DAL
XRAY
DVN
DXCM
FANG
DLR
DFS
DISCA
DISCK
DISH
DG
DLTR
D
DPZ
DOV
DOW
DTE
DUK
DRE
DD
DXC
EMN
ETN
EBAY
ECL
EIX
EW
EA
EMR
ENPH
ETR
EOG
EFX
EQIX
EQR
ESS
EL
ETSY
EVRG
ES
RE
EXC
EXPE
EXPD
EXR
XOM
FFIV
FB
FAST
FRT
FDX
FIS
FITB
FE
FRC
FISV
FLT
FMC
F
FTNT
FTV
FBHS
FOXA
FOX
BEN
FCX
GPS
GRMN
IT
GNRC
GD
GE
GIS
GM
GPC
GILD
GL
GPN
GS
GWW
HAL
HBI
HIG
HAS
HCA
PEAK
HSIC
HSY
HES
HPE
HLT
HOLX
HD
HON
HRL
HST
HWM
HPQ
HUM
HBAN
HII
IEX
IDXX
INFO
ITW
ILMN
INCY
IR
INTC
ICE
IBM
IP
IPG
IFF
INTU
ISRG
IVZ
IPGP
IQV
IRM
JKHY
J
JBHT
SJM
JNJ
JCI
JPM
JNPR
KSU
K
KEY
KEYS
KMB
KIM
KMI
KLAC
KHC
KR
LHX
LH
LRCX
LW
LVS
LEG
LDOS
LEN
LLY
LNC
LIN
LYV
LKQ
LMT
L
LOW
LUMN
LYB
MTB
MRO
MPC
MKTX
MAR
MMC
MLM
MAS
MA
MTCH
MKC
MCD
MCK
MDT
MRK
MET
MTD
MGM
MCHP
MU
MSFT
MAA
MRNA
MHK
TAP
MDLZ
MPWR
MNST
MCO
MS
MOS
MSI
MSCI
NDAQ
NTAP
NFLX
NWL
NEM
NWSA
NWS
NEE
NLSN
NKE
NI
NSC
NTRS
NOC
NLOK
NCLH
NRG
NUE
NVDA
NVR
NXPI
ORLY
OXY
ODFL
OMC
OKE
ORCL
OGN
OTIS
PCAR
PKG
PH
PAYX
PAYC
PYPL
PENN
PNR
PBCT
PEP
PKI
PFE
PM
PSX
PNW
PXD
PNC
POOL
PPG
PPL
PFG
PG
PGR
PLD
PRU
PTC
PEG
PSA
PHM
PVH
QRVO
PWR
QCOM
DGX
RL
RJF
RTX
O
REG
REGN
RF
RSG
RMD
RHI
ROK
ROL
ROP
ROST
RCL
SPGI
CRM
SBAC
SLB
STX
SEE
SRE
NOW
SHW
SPG
SWKS
SNA
SO
LUV
SWK
SBUX
STT
STE
SYK
SIVB
SYF
SNPS
SYY
TMUS
TROW
TTWO
TPR
TGT
TEL
TDY
TFX
TER
TSLA
TXN
TXT
TMO
TJX
TSCO
TT
TDG
TRV
TRMB
TFC
TWTR
TYL
TSN
UDR
ULTA
USB
UAA
UA
UNP
UAL
UNH
UPS
URI
UHS
VLO
VTR
VRSN
VRSK
VZ
VRTX
VFC
VIAC
VTRS
V
VNO
VMC
WRB
WAB
WMT
WBA
DIS
WM
WAT
WEC
WFC
WELL
WST
WDC
WU
WRK
WY
WHR
WMB
WLTW
WYNN
XEL
XLNX
XYL
YUM
ZBRA
ZBH
ZION
ZTS

In [149]:
df = pd.DataFrame()

In [150]:
df.shape

(0, 0)

In [151]:
df['stock_list']= stock_list
df['pegRatio_list']= pegRatio_list
df['ytd_list']= ytd_list
df['currentRatio_list'] = currentRatio_list
#df['book_value'] = book_value
df['dividend_yield'] = dividend_yield
df['moving_average_200'] = moving_average_200 
df['priceToBook'] = priceToBook

df = df.dropna()

In [152]:
df.shape

(289, 7)

In [153]:
list(df.columns)

['stock_list',
 'pegRatio_list',
 'ytd_list',
 'currentRatio_list',
 'dividend_yield',
 'moving_average_200',
 'priceToBook']

In [154]:
from sklearn.preprocessing import MinMaxScaler

#normData = pd.DataFrame(scaler.transform(df), index=df.index, columns=df.columns)
#scalers = {}
# def norm(columns):
#     for column in columns:
#         min_max_scaler = MinMaxScaler()
#         df[["A", "B"]] = min_max_scaler.fit_transform(df[["A", "B"]])
cols_to_norm = list(df.columns)
cols_to_norm.remove("ytd_list")
cols_to_norm.remove("stock_list")
cols_to_norm.remove("pegRatio_list")
df[cols_to_norm] = df[cols_to_norm].apply(lambda x: (x - x.min()) / (x.max() - x.min()))

In [155]:
df.head()

,stock_list,pegRatio_list,ytd_list,currentRatio_list,dividend_yield,moving_average_200,priceToBook
0,MMM,2.19,0.160166,0.130369,0.411175,0.218342,0.009948
1,ABT,2.31,0.152429,0.135380,0.242120,0.127560,0.008367
2,ABBV,1.90,0.303594,0.064747,0.604585,0.119409,0.021866
4,ACN,3.39,0.493229,0.092269,0.223496,0.343146,0.014983
5,ATVI,1.53,-0.068728,0.377028,0.078797,0.091983,0.004486

In [156]:
corrM = df.corr()
corrM

,pegRatio_list,ytd_list,currentRatio_list,dividend_yield,moving_average_200,priceToBook
pegRatio_list,1.000000,-0.069038,0.051214,0.015311,0.024599,-0.013477
ytd_list,-0.069038,1.000000,0.069359,0.080953,-0.030743,-0.047808
currentRatio_list,0.051214,0.069359,1.000000,-0.226655,0.149175,-0.036842
dividend_yield,0.015311,0.080953,-0.226655,1.000000,-0.435916,-0.071555
moving_average_200,0.024599,-0.030743,0.149175,-0.435916,1.000000,0.057594
priceToBook,-0.013477,-0.047808,-0.036842,-0.071555,0.057594,1.000000

In [157]:
df['bins'] = pd.qcut(df['pegRatio_list'], 10, labels = ['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th'])
df['bins'].value_counts().sort_index()

1st     29
2nd     30
3rd     28
4th     30
5th     29
6th     27
7th     29
8th     29
9th     30
10th    28
Name: bins, dtype: int64

In [158]:
df

,stock_list,pegRatio_list,ytd_list,currentRatio_list,dividend_yield,moving_average_200,priceToBook,bins
0,MMM,2.19,0.160166,0.130369,0.411175,0.218342,0.009948,6th
1,ABT,2.31,0.152429,0.135380,0.242120,0.127560,0.008367,6th
2,ABBV,1.90,0.303594,0.064747,0.604585,0.119409,0.021866,5th
4,ACN,3.39,0.493229,0.092269,0.223496,0.343146,0.014983,8th
5,ATVI,1.53,-0.068728,0.377028,0.078797,0.091983,0.004486,4th
...,...,...,...,...,...,...,...,...
495,XEL,3.75,-0.080367,0.063077,0.405444,0.066711,0.002521,9th
496,XLNX,4.88,0.506774,0.436207,0.230659,0.145981,0.018657,9th
497,XYL,2.34,0.653383,0.139755,0.161891,0.127343,0.011271,7th
500,ZBH,1.70,0.114390,0.138164,0.106017,0.174541,0.002710,5th
502,ZTS,3.41,0.196371,0.260818,0.078797,0.204102,0.034057,8th

In [159]:
#df["pegRatio_list"]()
#df[df["pegRatio_list"] == df["pegRatio_list"].range()]
#df[df["pegRatio_list"] == df["pegRatio_list"].max()]

In [161]:
y_bins = df.groupby('bins')['ytd_list'].mean()
x = df.groupby('bins')[['pegRatio_list','priceToBook','moving_average_200','dividend_yield','currentRatio_list']].mean()
y_10 = y_bins[9:10]
y_1 = y_bins[:1]


y = y_1[0]-y_10[0]
#x = x_1 - x_10
print(y_bins)

bins
1st     0.629033
2nd     0.537102
3rd     0.425613
4th     0.399918
5th     0.380994
6th     0.380393
7th     0.395533
8th     0.195798
9th     0.236321
10th    0.284418
Name: ytd_list, dtype: float64

In [162]:
x.head()

,pegRatio_list,priceToBook,moving_average_200,dividend_yield,currentRatio_list
bins,,,,,
1st,-7.923448,0.004585,0.085168,0.394378,0.096147
2nd,0.599333,0.009046,0.118213,0.377459,0.179057
3rd,1.110000,0.061868,0.189577,0.292519,0.140559
4th,1.454667,0.011483,0.192621,0.284575,0.118724
5th,1.850345,0.013203,0.181780,0.266130,0.121466

In [111]:
x.loc["10th", "pegRatio_list"]

34.18535714285715

In [147]:
bin_1

,stock_list,pegRatio_list,ytd_list,currentRatio_list,dividend_yield,moving_average_200,priceToBook,bins,range_peg,range_priceToBook,range_moving_average_200
20,ALL,-10.85,0.422886,0.096285,0.171152,0.138713,0.001269,1st,45.035357,0.006485,-0.007143
35,AME,-24.18,0.294840,0.066616,0.348803,0.143553,0.006042,1st,58.365357,0.001712,-0.011983
80,COG,0.24,0.010046,0.070832,0.242786,0.006149,0.004078,1st,33.945357,0.003676,0.125421
103,CVX,-2.97,0.392128,0.060889,-0.195610,0.107740,0.001196,1st,37.155357,0.006558,0.023830
123,COP,-6.62,0.730768,-0.013562,0.068000,0.052458,0.001973,1st,40.805357,0.005781,0.079113
146,DFS,0.13,1.345059,0.059696,0.128172,0.124076,0.003760,1st,34.055357,0.003994,0.007494
171,EOG,0.15,0.889548,0.016187,0.245651,0.075178,0.002268,1st,34.035357,0.005485,0.056392
180,RE,0.10,0.308048,0.026845,0.100952,0.290714,0.000629,1st,34.085357,0.007125,-0.159144
181,EXC,-38.34,0.432981,0.077911,-0.050911,0.040494,0.001315,1st,72.525357,0.006439,0.091076
193,FE,-8.54,0.346294,0.099228,-0.161226,0.030039,0.003136,1st,42.725357,0.004618,0.101532
211,GE,0.19,1.144744,0.010221,0.073731,0.110204,0.037609,1st,33.995357,-0.029856,0.021366
228,HES,-1.52,0.947695,0.029073,0.172585,0.076292,0.004844,1st,35.705357,0.002910,0.055278
276,KHC,-4.77,0.283115,0.062401,-0.204206,0.033045,0.000374,1st,38.955357,0.007379,0.098525
287,LNC,0.16,1.321803,-0.008153,0.086625,0.063034,0.000000,1st,34.025357,0.007754,0.068536
295,LYB,0.10,0.420462,-0.001551,-0.202773,0.108438,0.004246,1st,34.085357,0.003508,0.023132
297,MRO,-4.88,2.286573,0.049276,0.209834,0.000000,0.000388,1st,39.065357,0.007366,0.131570
298,MPC,-3.84,1.034812,-0.003301,-0.095323,0.054061,0.001689,1st,38.025357,0.006065,0.077509
345,NRG,0.27,0.472424,0.064071,0.251381,0.032316,0.009240,1st,33.915357,-0.001486,0.099254
346,NUE,0.20,1.261361,-0.093104,0.039347,0.100913,0.002861,1st,33.985357,0.004893,0.030657
371,PSX,-3.54,0.393616,0.067809,-0.102487,0.079395,0.001502,1st,37.725357,0.006252,0.052175
373,PXD,0.20,0.746181,0.110126,0.340207,0.168973,0.001741,1st,33.985357,0.006013,-0.037403
377,PPL,-1.56,0.122722,0.050549,-0.300194,0.020053,0.001898,1st,35.745357,0.005856,0.111517
380,PGR,-2.18,0.008310,0.122057,0.112413,0.100464,0.003707,1st,36.365357,0.004047,0.031107
381,PLD,-10.08,0.272210,0.075843,0.063702,0.129509,0.003565,1st,44.265357,0.004189,0.002062
391,DGX,-1.58,0.394539,0.043947,0.168287,0.148241,0.003498,1st,35.765357,0.004256,-0.016671
443,TJX,0.19,0.270604,0.033447,0.251381,0.067211,0.019504,1st,33.995357,-0.011751,0.064359
453,UDR,-12.47,0.647906,0.136374,-0.026555,0.044575,0.007117,1st,46.655357,0.000637,0.086995
464,VLO,-41.79,0.694245,0.045617,-0.209937,0.071390,0.001304,1st,75.975357,0.006450,0.060180
465,VTR,-52.00,0.346026,0.110842,-0.313088,0.052647,0.002224,1st,86.185357,0.005530,0.078923

bins
1st     0.629033
2nd     0.537102
3rd     0.425613
4th     0.399918
5th     0.380994
6th     0.380393
7th     0.395533
8th     0.195798
9th     0.236321
10th    0.284418
Name: ytd_list, dtype: float64

In [186]:
bin_1 = df[df["bins"] == "1st"]
bin_1["range_peg"] = bin_1["pegRatio_list"].apply(lambda num: x.loc["10th", "pegRatio_list"] - num)
bin_1["range_priceToBook"] = bin_1["priceToBook"].apply(lambda num: x.loc["10th", "priceToBook"] - num)
bin_1["range_moving_average_200"] = bin_1["moving_average_200"].apply(lambda num: x.loc["10th", "moving_average_200"] - num)
bin_1["range_dividend_yield"] = bin_1["dividend_yield"].apply(lambda num: x.loc["10th", "dividend_yield"] - num)
bin_1["range_currentRatio_list"] = bin_1["currentRatio_list"].apply(lambda num: x.loc["10th", "currentRatio_list"] - num)
bin_1['range_ytd_list'] = bin_1["ytd_list"].apply(lambda num: y_bins.iloc[9] - num)

C:\Users\rudra\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\rudra\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\rudra\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\rudra\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\rudra\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\rudra\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

In [187]:
bin_1.head()

,stock_list,pegRatio_list,ytd_list,currentRatio_list,dividend_yield,moving_average_200,priceToBook,bins,range_peg,range_priceToBook,range_moving_average_200,range_dividend_yield,range_currentRatio_list,range_ytd_list
20,ALL,-10.85,0.422886,0.050430,0.265043,0.138713,0.001269,1st,45.035357,0.006485,-0.007143,0.171152,0.096285,-0.138469
35,AME,-24.18,0.294840,0.080099,0.087393,0.143553,0.006042,1st,58.365357,0.001712,-0.011983,0.348803,0.066616,-0.010422
80,COG,0.24,0.010046,0.075883,0.193410,0.006149,0.004078,1st,33.945357,0.003676,0.125421,0.242786,0.070832,0.274372
103,CVX,-2.97,0.392128,0.085826,0.631805,0.107740,0.001196,1st,37.155357,0.006558,0.023830,-0.195610,0.060889,-0.107710
123,COP,-6.62,0.730768,0.160277,0.368195,0.052458,0.001973,1st,40.805357,0.005781,0.079113,0.068000,-0.013562,-0.446350

In [188]:
bin_1[["range_peg"]] = bin_1[["range_peg"]].apply(lambda x: (x - x.min()) / (x.max() - x.min())) 
bin_1.head()

C:\Users\rudra\Anaconda3\lib\site-packages\pandas\core\frame.py:3188: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

,stock_list,pegRatio_list,ytd_list,currentRatio_list,dividend_yield,moving_average_200,priceToBook,bins,range_peg,range_priceToBook,range_moving_average_200,range_dividend_yield,range_currentRatio_list,range_ytd_list
20,ALL,-10.85,0.422886,0.050430,0.265043,0.138713,0.001269,1st,0.212742,0.006485,-0.007143,0.171152,0.096285,-0.138469
35,AME,-24.18,0.294840,0.080099,0.087393,0.143553,0.006042,1st,0.467764,0.001712,-0.011983,0.348803,0.066616,-0.010422
80,COG,0.24,0.010046,0.075883,0.193410,0.006149,0.004078,1st,0.000574,0.003676,0.125421,0.242786,0.070832,0.274372
103,CVX,-2.97,0.392128,0.085826,0.631805,0.107740,0.001196,1st,0.061986,0.006558,0.023830,-0.195610,0.060889,-0.107710
123,COP,-6.62,0.730768,0.160277,0.368195,0.052458,0.001973,1st,0.131816,0.005781,0.079113,0.068000,-0.013562,-0.446350

In [189]:
X = bin_1[["range_peg", "range_priceToBook", "range_moving_average_200", "range_dividend_yield", "range_currentRatio_list"]]
y = bin_1["range_ytd_list"]

In [190]:
y

20    -0.138469
35    -0.010422
80     0.274372
103   -0.107710
123   -0.446350
146   -1.060641
171   -0.605130
180   -0.023631
181   -0.148563
193   -0.061876
211   -0.860326
228   -0.663277
276    0.001303
287   -1.037385
295   -0.136045
297   -2.002155
298   -0.750394
345   -0.188006
346   -0.976943
371   -0.109198
373   -0.461763
377    0.161696
380    0.276108
381    0.012208
391   -0.110121
443    0.013814
453   -0.363488
464   -0.409828
465   -0.061609
Name: range_ytd_list, dtype: float64

In [191]:
X

,range_peg,range_priceToBook,range_moving_average_200,range_dividend_yield,range_currentRatio_list
20,0.212742,0.006485,-0.007143,0.171152,0.096285
35,0.467764,0.001712,-0.011983,0.348803,0.066616
80,0.000574,0.003676,0.125421,0.242786,0.070832
103,0.061986,0.006558,0.023830,-0.195610,0.060889
123,0.131816,0.005781,0.079113,0.068000,-0.013562
146,0.002678,0.003994,0.007494,0.128172,0.059696
171,0.002296,0.005485,0.056392,0.245651,0.016187
180,0.003252,0.007125,-0.159144,0.100952,0.026845
181,0.738665,0.006439,0.091076,-0.050911,0.077911
193,0.168548,0.004618,0.101532,-0.161226,0.099228
211,0.001531,-0.029856,0.021366,0.073731,0.010221
228,0.034245,0.002910,0.055278,0.172585,0.029073
276,0.096422,0.007379,0.098525,-0.204206,0.062401
287,0.002104,0.007754,0.068536,0.086625,-0.008153
295,0.003252,0.003508,0.023132,-0.202773,-0.001551
297,0.098527,0.007366,0.131570,0.209834,0.049276
298,0.078630,0.006065,0.077509,-0.095323,-0.003301
345,0.000000,-0.001486,0.099254,0.251381,0.064071
346,0.001339,0.004893,0.030657,0.039347,-0.093104
371,0.072891,0.006252,0.052175,-0.102487,0.067809
373,0.001339,0.006013,-0.037403,0.340207,0.110126
377,0.035011,0.005856,0.111517,-0.300194,0.050549
380,0.046872,0.004047,0.031107,0.112413,0.122057
381,0.198010,0.004189,0.002062,0.063702,0.075843
391,0.035393,0.004256,-0.016671,0.168287,0.043947
443,0.001531,-0.011751,0.064359,0.251381,0.033447
453,0.243734,0.000637,0.086995,-0.026555,0.136374
464,0.804668,0.006450,0.060180,-0.209937,0.045617
465,1.000000,0.005530,0.078923,-0.313088,0.110842

In [192]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [193]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [194]:
reg = LinearRegression().fit(X_train, y_train)

In [195]:
y_pred = reg.predict(X_test)

In [196]:
from sklearn.metrics import mean_squared_error

In [197]:
mean_squared_error(y_test, y_pred)

0.08328063581816755

In [198]:
import matplotlib.pyplot as plt

In [199]:
print(reg.coef_)
print(reg.intercept_)

[ 0.08791151 -2.7373099  -2.1428752  -0.49070269  3.63586088]
-0.4318176936373966

In [201]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

def get_betas(column):
    df['bins'] = pd.qcut(df[column], 10, labels = ['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th'])
    df['bins'].value_counts().sort_index()

    y_bins = df.groupby('bins')['ytd_list'].mean()
    x = df.groupby('bins')[['pegRatio_list','priceToBook','moving_average_200','dividend_yield','currentRatio_list']].mean()
    y_10 = y_bins[9:10]
    y_1 = y_bins[:1]

    y = y_1[0]-y_10[0]

    bin_1 = df[df["bins"] == "1st"]
    bin_1["range_peg"] = bin_1["pegRatio_list"].apply(lambda num: x.loc["10th", "pegRatio_list"] - num)
    bin_1["range_priceToBook"] = bin_1["priceToBook"].apply(lambda num: x.loc["10th", "priceToBook"] - num)
    bin_1["range_moving_average_200"] = bin_1["moving_average_200"].apply(lambda num: x.loc["10th", "moving_average_200"] - num)
    bin_1["range_dividend_yield"] = bin_1["dividend_yield"].apply(lambda num: x.loc["10th", "dividend_yield"] - num)
    bin_1["range_currentRatio_list"] = bin_1["currentRatio_list"].apply(lambda num: x.loc["10th", "currentRatio_list"] - num)
    bin_1['range_ytd_list'] = bin_1["ytd_list"].apply(lambda num: y_bins.iloc[9] - num)

    bin_1[["range_peg"]] = bin_1[["range_peg"]].apply(lambda x: (x - x.min()) / (x.max() - x.min())) 

    X = bin_1[["range_peg", "range_priceToBook", "range_moving_average_200", "range_dividend_yield", "range_currentRatio_list"]]
    y = bin_1["range_ytd_list"]

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
    reg = LinearRegression().fit(X_train, y_train)
    y_pred = reg.predict(X_test)
    y_pred = reg.predict(X_test)
    print("MSE:", mean_squared_error(y_test, y_pred))
    print("Betas:", reg.coef_)
    print("Intercept:", reg.intercept_)

In [206]:
cols = list(df.columns)
for item in ["stock_list", "bins", "ytd_list"]:
    cols.remove(item)
cols

['pegRatio_list',
 'currentRatio_list',
 'dividend_yield',
 'moving_average_200',
 'priceToBook']

In [208]:
for col in cols:
    print(col)
    get_betas(col)
    print("----------")

pegRatio_list
MSE: 0.08328063581816755
Betas: [ 0.08791151 -2.7373099  -2.1428752  -0.49070269  3.63586088]
Intercept: -0.4318176936373966
----------
currentRatio_list
MSE: 0.20299695261557327
Betas: [ -1.24261097  -7.5425672    1.38064324   0.64015878 -10.8318101 ]
Intercept: 3.850654536179781
----------
dividend_yield
MSE: 0.09109144306466224
Betas: [ 0.20009287 -3.78076826 -0.09133891  2.95941394 -0.46426533]
Intercept: -1.8312202846309302
----------
moving_average_200
MSE: 0.3468794879808559
Betas: [-0.18813337 -4.90236838  0.64765087  0.02049715  1.67819853]
Intercept: -0.2956431377279884
----------
priceToBook

C:\Users\rudra\Anaconda3\lib\site-packages\ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\rudra\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\rudra\Anaconda3\lib\site-packages\ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\rudra\Anaconda3\lib\site-packages\ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\rudra\Anaconda3\lib\site-packages\ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\rudra\Anaconda3\lib\site-packages\ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\rudra\Anaconda3\lib\site-packages\pandas\core\frame.py:3188: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]
C:\Users\rudra\Anaconda3\lib\site-packages\ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\rudra\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\rudra\Anaconda3\lib\site-packages\ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\rudra\Anaconda3\lib\site-packages\ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\rudra\Anaconda3\lib\site-packages\ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\rudra\Anaconda3\lib\site-packages\ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\rudra\Anaconda3\lib\site-packages\pandas\core\frame.py:3188: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]
C:\Users\rudra\Anaconda3\lib\site-packages\ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\rudra\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\rudra\Anaconda3\lib\site-packages\ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\rudra\Anaconda3\lib\site-packages\ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\rudra\Anaconda3\lib\site-packages\ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\rudra\Anaconda3\lib\site-packages\ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\rudra\Anaconda3\lib\site-packages\pandas\core\frame.py:3188: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]
C:\Users\rudra\Anaconda3\lib\site-packages\ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\rudra\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\rudra\Anaconda3\lib\site-packages\ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\rudra\Anaconda3\lib\site-packages\ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\rudra\Anaconda3\lib\site-packages\ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\rudra\Anaconda3\lib\site-packages\ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\rudra\Anaconda3\lib\site-packages\pandas\core\frame.py:3188: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]
C:\Users\rudra\Anaconda3\lib\site-packages\ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\rudra\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\rudra\Anaconda3\lib\site-packages\ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\rudra\Anaconda3\lib\site-packages\ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\rudra\Anaconda3\lib\site-packages\ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\rudra\Anaconda3\lib\site-packages\ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\rudra\Anaconda3\lib\site-packages\pandas\core\frame.py:3188: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

MSE: 1.1596385346550377
Betas: [-3.17810490e-01 -4.97163250e+02 -7.64969569e+00 -1.20232454e+00
 -1.28826830e-01]
Intercept: 58.42359514315687
----------

In [ ]:
model = sm.OLS(y,x, const = 1).fit()
model.summary()

In [209]:
reg = LinearRegression()

In [210]:
reg.fit(x,y)

ValueError: Expected 2D array, got 1D array instead:
array=[-29.62153725  -8.5622072  -94.86418012   0.34987267  -1.78194712].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [211]:
reg.coef_

AttributeError: 'LinearRegression' object has no attribute 'coef_'