In [1]:
import yfinance as yf
import re
import pandas as pd
from pandas import DataFrame, Series

In [2]:
%pylab inline
from datetime import datetime

Populating the interactive namespace from numpy and matplotlib

In [3]:
TSM = yf.Ticker('TSM')

In [4]:
df = TSM.history(period = '2y', interval = '60m')

In [5]:
df.shape

(3509, 7)

In [6]:
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Datetime,,,,,,,
2019-09-03 09:30:00-04:00,42.150002,42.160000,41.590000,41.689999,1532368,0.0,0
2019-09-03 10:30:00-04:00,41.680000,41.869999,41.610001,41.730000,657596,0.0,0
2019-09-03 11:30:00-04:00,41.724998,41.810001,41.650002,41.654999,349022,0.0,0
2019-09-03 12:30:00-04:00,41.650002,41.669998,41.599998,41.615002,324204,0.0,0
2019-09-03 13:30:00-04:00,41.615002,41.680000,41.575001,41.680000,307858,0.0,0
...,...,...,...,...,...,...,...
2021-08-30 11:30:00-04:00,119.089996,119.300003,118.950104,119.190002,619950,0.0,0
2021-08-30 12:30:00-04:00,119.199997,119.404999,119.080002,119.393799,526114,0.0,0
2021-08-30 13:30:00-04:00,119.394997,119.410004,119.230003,119.360199,566621,0.0,0
2021-08-30 14:30:00-04:00,119.370003,119.489998,119.300003,119.389999,775616,0.0,0
2021-08-30 15:30:00-04:00,119.394997,119.400002,118.959999,118.970001,758388,0.0,0

In [7]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, LSTM, BatchNormalization
from tensorflow.keras.callbacks import TensorBoard, ModelCheckpoint

In [8]:
RNN_df = df[['Close', 'Volume']]

In [26]:
#notes for prediction
seq_len = 150
future_period_predict = 3
ratio_to_predict= 'TSM' 

#classification target
def classify(current, future):
    if float(future)> float(current):
        return 1
    else:
        return 0
    
#shift timeseries down 3 spots for 3 hour prediction
three_hour_future = RNN_df['Close'].shift(-future_period_predict)

#create a 3 hour future column
RNN_df["3 hour future"] = three_hour_future

In [27]:
RNN_df=RNN_df.dropna()

#send close and 3d future to classify function
def grab_arguments(s):
    return classify(s[0],s[1])

#create a classification
RNN_df['target'] = RNN_df[['Close','3 hour future']].T.apply(grab_arguments)

<ipython-input-27-dcc6cd4d100b>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  RNN_df['target'] = RNN_df[['Close','3 hour future']].T.apply(grab_arguments)

In [28]:

RNN_df

                                Close   Volume  3 hour future  target
Datetime
2019-09-03 09:30:00-04:00   41.689999  1532368      41.615002       0
2019-09-03 10:30:00-04:00   41.730000   657596      41.680000       0
2019-09-03 11:30:00-04:00   41.654999   349022      41.755001       1
2019-09-03 12:30:00-04:00   41.615002   324204      41.709999       1
2019-09-03 13:30:00-04:00   41.680000   307858      42.799999       1
...                               ...      ...            ...     ...
2021-08-27 12:30:00-04:00  118.334999   587573     118.489998       1
2021-08-27 13:30:00-04:00  118.510002   489469     119.320000       1
2021-08-27 14:30:00-04:00  118.669998   632557     119.089996       1
2021-08-27 15:30:00-04:00  118.489998   910607     119.190002       1
2021-08-30 09:30:00-04:00  119.320000  2124465     119.393799       1

[3503 rows x 4 columns]

In [29]:
################################
##split into train and test set
#############################

#make sure index is sorted. probs already was
times = sorted(RNN_df.index)

# last 5% of time as test set
last_10pct = times[-int(0.1*len(times))]
print(last_10pct)

2021-06-18 10:30:00-04:00

In [30]:
# test set is last 10% and beyond
test_set = RNN_df[RNN_df.index >= last_10pct]
test_set
#train set is anything under the last 10%
train_set =RNN_df[(RNN_df.index < last_10pct)]
train_set

                                Close   Volume  3 hour future  target
Datetime
2019-09-03 09:30:00-04:00   41.689999  1532368      41.615002       0
2019-09-03 10:30:00-04:00   41.730000   657596      41.680000       0
2019-09-03 11:30:00-04:00   41.654999   349022      41.755001       1
2019-09-03 12:30:00-04:00   41.615002   324204      41.709999       1
2019-09-03 13:30:00-04:00   41.680000   307858      42.799999       1
...                               ...      ...            ...     ...
2021-06-17 12:30:00-04:00  119.250000   873216     119.129997       0
2021-06-17 13:30:00-04:00  119.660004   580393     117.025002       0
2021-06-17 14:30:00-04:00  119.544998   837971     115.832001       0
2021-06-17 15:30:00-04:00  119.129997  1138162     116.199997       0
2021-06-18 09:30:00-04:00  117.025002  3070007     115.949997       0

[3153 rows x 4 columns]

In [31]:
#Drop the right answer, 3 hour future
train_set = train_set.T.drop(['3 hour future']).T
test_set = test_set.T.drop(['3 hour future']).T
len(train_set)
len(test_set)

350

In [32]:
#test_set

In [33]:
## check for infinte values in your data

#train_set['Volume'].preprocessing.scale(train_set['Volume'])
import numpy as np
#check for inf as well as -inf
#mask1 = isinf(-train_set['Volume'])
#train_set[mask1]


#mask = isinf(test_set['Volume'])
#test_set[mask]

# mask = train_set['Volume'] == float(inf)
# train_set[mask]= 0

train_set.loc[(train_set['Volume'] == float("inf")),'Volume']=0
train_set[train_set["Volume"] == 0]

# Replacing infinite with nan
#train_set.replace([np.inf, -np.inf], np.nan, inplace=True)
  
# Dropping all the rows with nan values
#train_set.dropna(inplace=True)
  
# Printing df


# Replacing infinite with nan
#test_set.replace([np.inf, -np.inf], np.nan, inplace=True)
  
# Dropping all the rows with nan values
#test_set.dropna(inplace=True)
  
# Printing df
#len(test_set)
#len(train_set)
#find the infinite values to get rid of
# 2021-05-05 13:30:00-04:00
#train_set.T["2021-05-05 13:30:00-04:00"]
#drop that index or indices
#RNN_df=RNN_df[~RNN_df.isin([np.nan, np.inf, -np.inf]).any(1)]
#len(RNN_df)

                                Close  Volume  target
Datetime
2019-11-29 13:00:00-05:00   53.067402     0.0     0.0
2019-12-24 13:00:00-05:00   57.724602     0.0     1.0
2020-05-14 11:30:00-04:00   50.509998     0.0     1.0
2020-11-27 13:00:00-05:00   98.739998     0.0     0.0
2020-12-24 13:00:00-05:00  105.970001     0.0     1.0
2021-05-05 12:30:00-04:00  116.251900     0.0     0.0

In [34]:
mask = (test_set['Volume'] == float("inf"))
test_set[mask]

Empty DataFrame
Columns: [Close, Volume, target]
Index: []

In [35]:
#train_set = train_set.drop('2019-12-02 09:30:00-05:00')
#train_set = train_set.drop('2019-12-26 09:30:00-05:00')
#train_set = train_set.drop('2020-05-14 12:30:00-04:00')
#train_set = train_set.drop('2020-12-28 09:30:00-05:00')
#train_set = train_set.drop('2021-05-05 14:30:00-04:00')
#train_set = train_set.drop('2020-11-30 09:30:00-05:00')

In [36]:
###################
#Preprocessing - scale and normalize
#####################

#import preprocessing
from sklearn import preprocessing

# import deque continual appending to list and maintains list len
from collections import deque

import numpy as np
import random

def preprocess_df(df):
    df.dropna(inplace=True)
    
    for col in df:
        
        if col != "target":
            #normalize with % change 
            df[col] = df[col].pct_change()
            df.dropna(inplace=True)
            #scale the data
            df.loc[(df['Volume'] == float("inf")),'Volume']=0
            #print(df[df[col] == float("inf")])
            df[col]= preprocessing.scale(df[col].values)
        
    
    df.dropna(inplace = True)
    
    sequential_data = []
    #maintain the seq_len
    prev_days = deque(maxlen=seq_len)
    #turns df into a list of lists
    for i in df.values:
        # take each value except for target col in list
        prev_days.append([n for n in i[:-1]])
        #print(len(prev_days))
        if len(prev_days) == seq_len:
            sequential_data.append([np.array(prev_days), i[-1]])
            #print(sequential_data)
    
    random.shuffle(sequential_data)  
    
    #####################
    ### Balancet the Data 
    ######################

    buys = []
    sells = []
    for seq, target in sequential_data:
        if target == 0:
            sells.append([seq,target])
        elif target ==1:
            buys.append([seq,target])
     
    random.shuffle(buys)
    random.shuffle(sells)
    
    lower = min(len(buys), len(sells)) 
    buys = buys[:lower]
    sells = sells[:lower]
    #print(sells)
    sequential_data = buys+sells
    
    random.shuffle(sequential_data)
    
    x = []
    y = []
    
    for seq, target in sequential_data:
        x.append(seq)
        y.append(target)
        
    return np.array(x), y 

#preprocess_df(train_set)
train_x, train_y = preprocess_df(train_set)
test_x, test_y = preprocess_df(test_set)

In [37]:
print(f"train data:{len(train_x)} validation: {len(test_x)}")

train data:2922 validation: 196

In [38]:
print(f"Dont buys:{train_y.count(0)}, buys:{train_y.count(1)}")

Dont buys:1461, buys:1461

In [39]:
print(f"VALIDATION Dont buys: {test_y.count(0)}, buys: {test_y.count(1)}")

VALIDATION Dont buys: 98, buys: 98

In [40]:

epochs = 15
batch_size = 64
name = f"{seq_len}-SEQ-{future_period_predict}-PRED-{int(time.time())}"

In [41]:
# check to make sure training and test set are numpy arrays
test_y = np.asarray(test_y)
train_y = np.asarray(train_y)

In [42]:
model = Sequential()
model.add(LSTM(128, input_shape= (train_x.shape[1:]), return_sequences=True))
model.add(Dropout(0.2))
model.add(BatchNormalization())

model.add(LSTM(128, input_shape= (train_x.shape[1:]), return_sequences=True))
model.add(Dropout(0.1))
model.add(BatchNormalization())

model.add(LSTM(128, input_shape= (train_x.shape[1:])))
model.add(Dropout(0.2))
model.add(BatchNormalization())

model.add(tf.keras.layers.Flatten())
#dense layer activation rectified linear
model.add(Dense(32, activation ='relu'))
model.add(Dropout(0.2))

#output layer
model.add(Dense(2, activation = 'softmax'))

opt = tf.keras.optimizers.SGD(lr= 0.002, decay=1e-3)
model.compile(loss='sparse_categorical_crossentropy',
             optimizer = opt,
             metrics= ['accuracy'])

tensorboard = TensorBoard(log_dir = f'log/{name}')


checkpoint = ModelCheckpoint(filepath= r'C:\Users\chand\My Python\models',verbose=1, save_best_only=True)

history = model.fit(
            train_x, train_y,
            batch_size=batch_size,
            epochs=epochs,
            validation_data=(test_x, test_y),
            callbacks=[tensorboard, checkpoint])
#model.save('')

Epoch 1/15
 2/46 [>.............................] - ETA: 3:34 - loss: 1.2238 - accuracy: 0.4922WARNING:tensorflow:Callbacks method `on_train_batch_end` is slow compared to the batch time (batch time: 1.2511s vs `on_train_batch_end` time: 8.5057s). Check your callbacks.
46/46 [==============================] - ETA: 0s - loss: 1.0229 - accuracy: 0.4935
Epoch 00001: val_loss improved from inf to 0.69418, saving model to C:\Users\chand\My Python\models
INFO:tensorflow:Assets written to: C:\Users\chand\My Python\models\assets
46/46 [==============================] - 144s 3s/step - loss: 1.0229 - accuracy: 0.4935 - val_loss: 0.6942 - val_accuracy: 0.5000
Epoch 2/15
46/46 [==============================] - ETA: 0s - loss: 0.8914 - accuracy: 0.5096
Epoch 00002: val_loss did not improve from 0.69418
46/46 [==============================] - 78s 2s/step - loss: 0.8914 - accuracy: 0.5096 - val_loss: 0.6961 - val_accuracy: 0.5000
Epoch 3/15
46/46 [==============================] - ETA: 0s - loss: 0.8687 - accuracy: 0.4983
Epoch 00003: val_loss did not improve from 0.69418
46/46 [==============================] - 84s 2s/step - loss: 0.8687 - accuracy: 0.4983 - val_loss: 0.6950 - val_accuracy: 0.5000
Epoch 4/15
46/46 [==============================] - ETA: 0s - loss: 0.8391 - accuracy: 0.5185
Epoch 00004: val_loss did not improve from 0.69418
46/46 [==============================] - 83s 2s/step - loss: 0.8391 - accuracy: 0.5185 - val_loss: 0.6960 - val_accuracy: 0.5051
Epoch 5/15
46/46 [==============================] - ETA: 0s - loss: 0.8358 - accuracy: 0.5092
Epoch 00005: val_loss did not improve from 0.69418
46/46 [==============================] - 82s 2s/step - loss: 0.8358 - accuracy: 0.5092 - val_loss: 0.6950 - val_accuracy: 0.5306
Epoch 6/15
46/46 [==============================] - ETA: 0s - loss: 0.8122 - accuracy: 0.5257
Epoch 00006: val_loss did not improve from 0.69418
46/46 [==============================] - 84s 2s/step - loss: 0.8122 - accuracy: 0.5257 - val_loss: 0.6957 - val_accuracy: 0.5357
Epoch 7/15
46/46 [==============================] - ETA: 0s - loss: 0.8077 - accuracy: 0.5294
Epoch 00007: val_loss did not improve from 0.69418
46/46 [==============================] - 77s 2s/step - loss: 0.8077 - accuracy: 0.5294 - val_loss: 0.6980 - val_accuracy: 0.5306
Epoch 8/15
46/46 [==============================] - ETA: 0s - loss: 0.8016 - accuracy: 0.5301
Epoch 00008: val_loss did not improve from 0.69418
46/46 [==============================] - 83s 2s/step - loss: 0.8016 - accuracy: 0.5301 - val_loss: 0.6983 - val_accuracy: 0.5255
Epoch 9/15
46/46 [==============================] - ETA: 0s - loss: 0.7951 - accuracy: 0.5298
Epoch 00009: val_loss did not improve from 0.69418
46/46 [==============================] - 83s 2s/step - loss: 0.7951 - accuracy: 0.5298 - val_loss: 0.7040 - val_accuracy: 0.4847
Epoch 10/15
46/46 [==============================] - ETA: 0s - loss: 0.7982 - accuracy: 0.5311
Epoch 00010: val_loss did not improve from 0.69418
46/46 [==============================] - 80s 2s/step - loss: 0.7982 - accuracy: 0.5311 - val_loss: 0.7027 - val_accuracy: 0.4898
Epoch 11/15
46/46 [==============================] - ETA: 0s - loss: 0.7887 - accuracy: 0.5287
Epoch 00011: val_loss did not improve from 0.69418
46/46 [==============================] - 68s 1s/step - loss: 0.7887 - accuracy: 0.5287 - val_loss: 0.7093 - val_accuracy: 0.4796
Epoch 12/15
46/46 [==============================] - ETA: 0s - loss: 0.7945 - accuracy: 0.5175
Epoch 00012: val_loss did not improve from 0.69418
46/46 [==============================] - 67s 1s/step - loss: 0.7945 - accuracy: 0.5175 - val_loss: 0.7268 - val_accuracy: 0.5153
Epoch 13/15
46/46 [==============================] - ETA: 0s - loss: 0.7795 - accuracy: 0.5435
Epoch 00013: val_loss did not improve from 0.69418
46/46 [==============================] - 67s 1s/step - loss: 0.7795 - accuracy: 0.5435 - val_loss: 0.7310 - val_accuracy: 0.5561
Epoch 14/15
46/46 [==============================] - ETA: 0s - loss: 0.7850 - accuracy: 0.5243
Epoch 00014: val_loss did not improve from 0.69418
46/46 [==============================] - 67s 1s/step - loss: 0.7850 - accuracy: 0.5243 - val_loss: 0.7613 - val_accuracy: 0.4592
Epoch 15/15
46/46 [==============================] - ETA: 0s - loss: 0.7827 - accuracy: 0.5222
Epoch 00015: val_loss did not improve from 0.69418
46/46 [==============================] - 72s 2s/step - loss: 0.7827 - accuracy: 0.5222 - val_loss: 0.7863 - val_accuracy: 0.4847